@startuml
class App
{
    +readProduct(JsonReader reader, String productName):boolean
    +readJson(JsonReader reader, String input):boolean
    +main(String[] args):void
}

file exercise44_input.json{

}

App <-> exercise44_input.json

@enduml